[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "evalia"
version = "1.0.0"
description = "EVALIA - Evaluación con IA"
authors = [
    { name = "José Miguel Santos", email = "josemiguel.santos@ulpgc.es" },
    { name = "Cayetano Guerra", email = "cayetano.guerra@ulpgc.es" },
    { name = "Pedro Romero Suárez", email = "pedro.romero105@alu.ulpgc.es" }
]
readme = "README.md"
# TODO: Add license file
# license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = [ "pandas", "openpyxl", "openai", "tiktoken", "platformdirs", "google-genai", "google-cloud-storage", "anthropic", "pyyaml" ]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["evalia*"]

